---
language: bash
services: docker

dist: xenial

env:
  - VERSION=12-master
  - VERSION=12-3.0
  - VERSION=12-3.0 VARIANT=alpine
  - VERSION=12-2.5
  - VERSION=12-2.5 VARIANT=alpine
  - VERSION=11-3.0
  - VERSION=11-3.0 VARIANT=alpine
  - VERSION=11-2.5
  - VERSION=11-2.5 VARIANT=alpine
  - VERSION=10-3.0
  - VERSION=10-3.0 VARIANT=alpine
  - VERSION=10-2.5
  - VERSION=10-2.5 VARIANT=alpine
  - VERSION=9.6-3.0
  - VERSION=9.6-3.0 VARIANT=alpine
  - VERSION=9.6-2.5
  - VERSION=9.6-2.5 VARIANT=alpine
  - VERSION=9.5-3.0
  - VERSION=9.5-3.0 VARIANT=alpine
  - VERSION=9.5-2.5
  - VERSION=9.5-2.5 VARIANT=alpine

jobs:
  allow_failures:
    - env: VERSION=12-master

script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
        echo "$DOCKERHUB_ACCESS_TOKEN" | docker login -u $DOCKERHUB_USERNAME --password-stdin &&
        make push ;
    else
        make test ;
    fi
