---
language: bash
services: docker

dist: xenial

env:
  - VERSION=12-3.0
  - VERSION=12-3.0 VARIANT=alpine
  - VERSION=12-2.5
  - VERSION=12-2.5 VARIANT=alpine
  - VERSION=11-3.0
  - VERSION=11-3.0 VARIANT=alpine
  - VERSION=11-2.5
  - VERSION=11-2.5 VARIANT=alpine
  - VERSION=10-3.0
  - VERSION=10-3.0 VARIANT=alpine
  - VERSION=10-2.5
  - VERSION=10-2.5 VARIANT=alpine
  - VERSION=9.6-3.0
  - VERSION=9.6-3.0 VARIANT=alpine
  - VERSION=9.6-2.5
  - VERSION=9.6-2.5 VARIANT=alpine
  - VERSION=9.5-3.0
  - VERSION=9.5-3.0 VARIANT=alpine
  - VERSION=9.5-2.5
  - VERSION=9.5-2.5 VARIANT=alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | grep -E "VARIANT|VERSION" | sort
  - cd "$VERSION/$VARIANT"
  - image="postgis/postgis:$VERSION${VARIANT:+-${VARIANT}}"

script:
  - docker build --pull -t "$image" .
  - ~/official-images/test/run.sh -c ~/official-images/test/config.sh -c "../${VARIANT:+../}test/postgis-config.sh" "$image"
